services:
  userservice:
    image: rasmussig/user-services:1.0.0
    container_name: userservice
    platform: linux/amd64
    ports:
      - "80:8080"
    environment:
      - DatabaseName=4SemProj
      - collectionName=User
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always

  authservice:
    image: rasmussig/auth-service:1.0.0
    container_name: authservice
    platform: linux/amd64
    ports:
      - "81:8080"
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - userservicehost=http://userservice:8080
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always

  catalogservice:
    image: rasmussig/catalog-service:1.0.1
    container_name: catalogservice     
    platform: linux/amd64
    ports:
      - "82:8080"
    environment:
      - DatabaseName=4SemProj
      - collectionName=Catalog
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always

  auctionservice:
    image: rasmussig/auction-service-image:1.0.1
    container_name: auctionservice
    platform: linux/amd64
    ports:
      - "83:8080"
    environment:
      - DatabaseName=4SemProj
      - collectionName=Auction
      - QueueHostName=rabbitmq
      - vaultConnectionString=https://vaulthost:8201
      - catalogservicehost=http://catalogservice:8080
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always

  biddingservice:
    image: rasmussig/bidding-service:1.0.2
    container_name: biddingservice
    platform: linux/amd64
    ports:
      - "84:8080"
    environment:
      - DatabaseName=4SemProj
      - collectionName=Bids
      - QueueHostName=rabbitmq
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:  # Sikrer, at microservices er klar, før NGINX starter
      - userservice
      - authservice
      - catalogservice
      - auctionservice
      - biddingservice
    networks:
      - go_infrastructure_auctionnetwork

networks:
  go_infrastructure_auctionnetwork:
    driver: bridge
    external: true
