services:
  userservice:
    image: rasmussig/user-services:1.0.0
    container_name: userservice
    platform: linux/amd64  # Tving brug af AMD64
    ports:
      - "80:8080"
    environment:
      - MongoConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=User
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always


  authservice:
    image: rasmussig/auth-service:1.0.0
    container_name: authservice
    platform: linux/amd64  # Tving brug af AMD64
    ports:
      - "81:8080"
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - userservicehost=http://userservice:8080
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always

  catalogservice:
    image: rasmussig/catalog-service:1.0.1
    container_name: catalogservice     
    platform: linux/amd64  # Tving brug af AMD64
    ports:
      - "82:8080"
    environment:
      - MongoConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=Catalog
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always

  auctionservice:
    image: rasmussig/auction-service-image:1.0.1
    container_name: auctionservice
    platform: linux/amd64  # Tving brug af AMD64
    ports:
      - "83:8080"
    environment:
      - DatabaseName=4SemProj
      - collectionName=Auction
      - QueueHostName=rabbitmq
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped
    pull_policy: always


networks:
  go_infrastructure_auctionnetwork:
    driver: bridge
    external: true
