version: '3.8'

services:
  userservice:
    image: rasmussig/user-services:1.0.0
    container_name: userservice
    ports:
      - "80:8080"
    environment:
      - MongoConnectionString=mongodb://admin:1234@mongodb:27017
      - DatabaseName=4SemProj
      - collectionName=User
      - vaultConnectionString=https://vaulthost:8201
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped

  authservice:
    image: rasmussig/auth-service:1.0.0
    container_name: authservice
    ports:
      - "81:8080"
    environment:
      - vaultConnectionString=https://vaulthost:8201
      - userservicehost=http://userservice:8080
    networks:
      - go_infrastructure_auctionnetwork
    restart: unless-stopped

networks:
  go_infrastructure_auctionnetwork:
    driver: bridge
    external: true
